//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labely.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupDetail
    {
        public long GDId { get; set; }
        public Nullable<long> GMId { get; set; }
        public string Lable1 { get; set; }
        public string Lable2 { get; set; }
        public string Lable3 { get; set; }
        public string Lable4 { get; set; }
        public string Lable5 { get; set; }
        public string Lable6 { get; set; }
        public string Lable7 { get; set; }
        public string Lable8 { get; set; }
        public string Lable9 { get; set; }
        public string Lable10 { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual GroupMaster GroupMaster { get; set; }
    }
}
